# Generated by Django 4.2 on 2024-09-14 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='年を入力')),
                ('month', models.CharField(choices=[('1月', '1月'), ('2月', '2月'), ('3月', '3月'), ('4月', '4月'), ('5月', '5月'), ('6月', '6月'), ('7月', '7月'), ('8月', '8月'), ('9月', '9月'), ('10月', '10月'), ('11月', '11月'), ('12月', '12月')], max_length=10, verbose_name='月を選択')),
                ('amount', models.CharField(max_length=7, verbose_name='金額を入力')),
                ('category', models.CharField(choices=[('家庭からの給付', '家庭からの給付'), ('日本学生支援機構の奨学金', '日本学生支援機構の奨学金'), ('日本学生支援機構以外の奨学金', '日本学生支援機構以外の奨学金'), ('アルバイト等収入', 'アルバイト等収入'), ('その他', 'その他')], max_length=14, verbose_name='カテゴリーを選択')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='年を入力')),
                ('month', models.CharField(choices=[('1月', '1月'), ('2月', '2月'), ('3月', '3月'), ('4月', '4月'), ('5月', '5月'), ('6月', '6月'), ('7月', '7月'), ('8月', '8月'), ('9月', '9月'), ('10月', '10月'), ('11月', '11月'), ('12月', '12月')], max_length=10, verbose_name='月を選択')),
                ('amount', models.CharField(max_length=7, verbose_name='金額を入力')),
                ('category', models.CharField(choices=[('学費', '学費'), ('修学費', '修学費'), ('食費', '食費'), ('光熱水料通信費', '光熱水料通信費'), ('その他', 'その他')], max_length=7, verbose_name='カテゴリーを選択')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
