# Generated by Django 4.2 on 2024-09-09 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='年を入力')),
                ('month', models.CharField(choices=[('january', '1月'), ('february', '2月'), ('march', '3月'), ('april', '4月'), ('may', '5月'), ('june', '6月'), ('july', '7月'), ('august', '8月'), ('september', '9月'), ('october', '10月'), ('november', '11月'), ('december', '12月')], max_length=10, verbose_name='月を選択')),
                ('category', models.CharField(choices=[('From family', '家庭からの給付'), ('Scholarship', '日本学生支援機構の奨学金'), ('Other scholarship', '日本学生支援機構以外の奨学金'), ('Income from PT job etc.', 'アルバイト等収入'), ('Other', 'その他')], max_length=25, verbose_name='カテゴリーを選択')),
                ('amount', models.CharField(max_length=7, verbose_name='金額を入力：円')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
